// Document-level markdown generators — one per output document type.
// Content is always generated fresh from current engagement form data.
// Delegates to existing form-key generators where appropriate.

import { generateMarkdown } from '../data/templateMappings.js';

function header(eng, title) {
  return `# ${title}

**Client:** ${eng.clientName}
**Company:** ${eng.company}
**Contact:** ${eng.primaryContact} (${eng.email})
**Start Date:** ${eng.startDate}
**Owner:** ${eng.owner}

---`;
}

const DOCUMENT_GENERATORS = {

  // ── AI Readiness Assessment ──────────────────────────────────────────────

  'executive-summary': (eng) => {
    const intake    = eng.forms?.intake        ?? {};
    const scoring   = eng.forms?.scoring       ?? {};
    const useCases  = eng.forms?.['use-cases'] ?? {};
    const vi = k => intake[k]   || '—';
    const vs = k => scoring[k]  || '—';
    const vu = k => useCases[k] || '—';

    const scoreDims = [
      ['Data Availability',             vs('dataAvailability')],
      ['Data Quality',                  vs('dataQuality')],
      ['Technical Infrastructure',      vs('technicalReadiness')],
      ['Team Change Adoption',          vs('teamAdoption')],
      ['Business Process Maturity',     vs('processMaturity')],
    ];
    const nums = scoreDims.map(([, s]) => parseInt(s)).filter(n => !isNaN(n));
    const avg = nums.length > 0
      ? (nums.reduce((a, b) => a + b, 0) / nums.length).toFixed(1)
      : '—';

    return `${header(eng, 'AI Readiness Assessment – Executive Summary')}

## Overview

${eng.company} engaged Barinhall LLC to assess its AI readiness and identify high-impact automation opportunities. This executive summary presents the key findings and recommended next steps.

| Field | Value |
|---|---|
| Industry | ${vi('industry')} |
| Primary Decision-Maker | ${vi('decisionMaker')} |
| Current AI / Automation Experience | ${vi('aiExperience')} |
| Estimated Budget | ${vi('budget')} |
| Target Timeline | ${vi('timeline')} |

## AI Readiness Score

**Composite Readiness Score: ${avg} / 5.0**

| Dimension | Score (1–5) |
|---|---|
${scoreDims.map(([label, score]) => `| ${label} | ${score} |`).join('\n')}

## Key Operational Pain Points

${vi('painPoints')}

## Assessment Findings

${vs('scoringNotes')}

## Recommended Use Cases

| # | Use Case | Impact | Effort |
|---|---|---|---|
| 1 | ${vu('useCase1')} | ${vu('useCase1Impact')} | ${vu('useCase1Effort')} |
| 2 | ${vu('useCase2')} | ${vu('useCase2Impact')} | ${vu('useCase2Effort')} |
| 3 | ${vu('useCase3')} | ${vu('useCase3Impact')} | ${vu('useCase3Effort')} |

## Top Recommended Next Step

${vu('topRecommendation')}

---
*Generated by Barinhall Delivery Hub*
`;
  },

  'readiness-report': (eng) => {
    const intake   = eng.forms?.intake        ?? {};
    const scoring  = eng.forms?.scoring       ?? {};
    const useCases = eng.forms?.['use-cases'] ?? {};
    const vi = k => intake[k]   || '—';
    const vs = k => scoring[k]  || '—';
    const vu = k => useCases[k] || '—';

    const scoreDims = [
      ['Data Availability',         vs('dataAvailability')],
      ['Data Quality',              vs('dataQuality')],
      ['Technical Infrastructure',  vs('technicalReadiness')],
      ['Team Change Adoption',      vs('teamAdoption')],
      ['Business Process Maturity', vs('processMaturity')],
    ];
    const nums = scoreDims.map(([, s]) => parseInt(s)).filter(n => !isNaN(n));
    const avg = nums.length > 0
      ? (nums.reduce((a, b) => a + b, 0) / nums.length).toFixed(1)
      : '—';

    return `${header(eng, 'AI Readiness Assessment – Full Report')}

## Part 1 — Client Profile

| Field | Response |
|---|---|
| Industry | ${vi('industry')} |
| Employees | ${vi('employeeCount')} |
| AI / Automation Experience | ${vi('aiExperience')} |
| Decision-Maker | ${vi('decisionMaker')} |
| Budget Range | ${vi('budget')} |
| Desired Timeline | ${vi('timeline')} |

### Current Tools & Software

${vi('currentTools')}

### Top Operational Pain Points

${vi('painPoints')}

---

## Part 2 — Readiness Scoring

**Composite Readiness Score: ${avg} / 5.0**

| Dimension | Score (1–5) |
|---|---|
${scoreDims.map(([label, score]) => `| ${label} | ${score} |`).join('\n')}

### Scoring Rationale & Observations

${vs('scoringNotes')}

---

## Part 3 — Use Case Prioritization

### Use Case Matrix

| # | Use Case | Impact | Effort |
|---|---|---|---|
| 1 | ${vu('useCase1')} | ${vu('useCase1Impact')} | ${vu('useCase1Effort')} |
| 2 | ${vu('useCase2')} | ${vu('useCase2Impact')} | ${vu('useCase2Effort')} |
| 3 | ${vu('useCase3')} | ${vu('useCase3Impact')} | ${vu('useCase3Effort')} |

### Top Recommendation

${vu('topRecommendation')}

---
*Generated by Barinhall Delivery Hub*
`;
  },

  // ── AI Strategy & Roadmap ────────────────────────────────────────────────

  'roadmap-summary': (eng) => {
    const roadmap = eng.forms?.roadmap ?? {};
    const v = k => roadmap[k] || '—';

    return `${header(eng, 'AI Strategy & Roadmap – Roadmap Summary')}

## Initiative Roadmap

| Phase | Initiative | Timeline | Owner |
|---|---|---|---|
| 1 | ${v('phase1Name')} | ${v('phase1Timeline')} | ${v('phase1Owner')} |
| 2 | ${v('phase2Name')} | ${v('phase2Timeline')} | ${v('phase2Owner')} |
| 3 | ${v('phase3Name')} | ${v('phase3Timeline')} | ${v('phase3Owner')} |

## Key Dependencies & Assumptions

${v('dependencies')}

## Definition of Success

${v('successDefinition')}

---
*Generated by Barinhall Delivery Hub*
`;
  },

  // ── 30-Day AI Pilot ──────────────────────────────────────────────────────

  'pilot-charter': (eng) => {
    const charter = eng.forms?.charter ?? {};
    const metrics = eng.forms?.metrics ?? {};
    const vc = k => charter[k] || '—';
    const vm = k => metrics[k] || '—';

    return `${header(eng, '30-Day AI Pilot – Charter')}

## Problem Statement

${vc('problemStatement')}

## Scope

${vc('pilotScope')}

## Pilot Details

| Field | Value |
|---|---|
| Tools / Platforms | ${vc('toolsUsed')} |
| Executive Sponsor | ${vc('executiveSponsor')} |
| Start Date | ${vc('pilotStartDate')} |
| End Date | ${vc('pilotEndDate')} |

## Pilot Team

${vc('teamMembers')}

## Success Metrics

| Metric | Baseline | Target |
|---|---|---|
| ${vm('primaryMetric')} | ${vm('primaryBaseline')} | ${vm('primaryTarget')} |

**Secondary Metrics:** ${vm('secondaryMetric1')}; ${vm('secondaryMetric2')}

**Measurement Frequency:** ${vm('measurementFrequency')}

## Qualitative Success Criteria

${vm('qualitativeGoals')}

---
*Generated by Barinhall Delivery Hub*
`;
  },

  // ── AI Governance & Risk Review ──────────────────────────────────────────

  'governance-findings-summary': (eng) => {
    const gov      = eng.forms?.governance ?? {};
    const findings = eng.forms?.findings   ?? {};
    const vg = k => gov[k]      || '—';
    const vf = k => findings[k] || '—';

    return `${header(eng, 'AI Governance & Risk Review – Findings Summary')}

## Executive Summary

${vf('executiveSummary')}

---

## Governance Controls Assessment

| Control Area | Status |
|---|---|
| AI Policies Documented | ${vg('aiPoliciesExist')} |
| Data Governance Practices | ${vg('dataGovernance')} |
| Vendor / Third-Party Oversight | ${vg('vendorOversight')} |
| AI Incident Response Plan | ${vg('incidentResponse')} |
| AI Ethics / Responsible-Use Training | ${vg('trainingProgram')} |

### Additional Governance Observations

${vg('governanceNotes')}

---

## Findings

### Finding #1 — Severity: ${vf('finding1Severity')}

${vf('finding1')}

### Finding #2 — Severity: ${vf('finding2Severity')}

${vf('finding2')}

### Finding #3 — Severity: ${vf('finding3Severity')}

${vf('finding3')}

---
*Generated by Barinhall Delivery Hub*
`;
  },

  // ── AI Team Training Session ─────────────────────────────────────────────

  'training-action-plan': (eng) => {
    const needs  = eng.forms?.needs          ?? {};
    const plan   = eng.forms?.['action-plan'] ?? {};
    const vn = k => needs[k] || '—';
    const vp = k => plan[k]  || '—';

    return `${header(eng, 'AI Team Training Session – Action Plan')}

## Training Context

| Field | Value |
|---|---|
| Target Audience | ${vn('audienceRole')} |
| Participants | ${vn('audienceSize')} |
| Current AI Skill Level | ${vn('currentSkillLevel')} |
| Delivery Format | ${vn('deliveryFormat')} |

### Training Goals

${vn('trainingGoals')}

---

## Action Items

| # | Action | Owner | Due |
|---|---|---|---|
| 1 | ${vp('action1')} | ${vp('action1Owner')} | ${vp('action1Due')} |
| 2 | ${vp('action2')} | ${vp('action2Owner')} | ${vp('action2Due')} |
| 3 | ${vp('action3')} | ${vp('action3Owner')} | ${vp('action3Due')} |

**Follow-Up Check-In:** ${vp('followUpDate')}

## Resources & Materials Shared

${vp('resources')}

---
*Generated by Barinhall Delivery Hub*
`;
  },

  // ── Managed AI Ops – Monthly ─────────────────────────────────────────────

  'monthly-ops-review': (eng) => {
    const review = eng.forms?.review ?? {};
    const v = k => review[k] || '—';

    return `${header(eng, `Managed AI Ops – Monthly Review Summary: ${v('month')}`)}

## Summary of Work Completed

${v('summaryOfWork')}

## KPI / Metrics Update

${v('kpiUpdates')}

## Client Feedback

${v('clientFeedback')}

## Highlights & Wins

${v('highlights')}

---
*Generated by Barinhall Delivery Hub*
`;
  },
};

export function generateDocument(docTypeId, engagement) {
  const gen = DOCUMENT_GENERATORS[docTypeId];
  if (!gen) return `# Generation Error\n\nNo generator found for document type: \`${docTypeId}\`\n`;
  return gen(engagement);
}
